# Generated by Django 5.1.3 on 2025-02-26 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidate",
            name="email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="phone",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
