services:
  backend:
    build:
      context: .
      dockerfile: docker/django/Dockerfile
    volumes:
      - .:/backend
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - postgres
    command: /start

  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}

volumes:
  postgres_data: