# Generated by Django 5.1.3 on 2025-02-26 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vacancies", "0002_alter_vacancy_company_alter_vacancy_salary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vacancy",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
    ]
